#! /bin/bash
gnatmake -P openid 1>&2 || exit 1

for f in *.ad?; do
   if [ ! -f ${f%.ad?}.ali ]; then
      echo $f
   fi
done \
  | egrep -v '^(util-log-loggers-traceback-gnat[.]adb|util-serialize-io-xml-get_location-xmlada-.[.]adb)$'
